config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'home', to: 'static_pages#home'
  get 'help', to: 'static_pages#help'

  resources :users, except: [:new, :put]

  get       '/signup', to: 'users#new'
  get       '/login',  to: 'sessions#new'
  post      '/login',  to: 'sessions#create'
  delete    '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :votes,               only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :votes, dependent: :destroy

  default_scope -> {order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, 
                      length: {maximum: 140}
  validate  :picture_size

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user,  only: [:create, :destroy]
  before_action :correct_user,    only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)

    if @micropost.save
      flash['success'] = "Micrpost created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micrpost deleted"
    redirect_to request.referrer || root_path
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>

    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <div class="content">
        <%= micropost.content %>
        <%= image_tag micropost.picture.url if micropost.picture? %>
    </div>
    <div class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago
        <% if current_user?(micropost.user) %>
            <%= link_to "delete", micropost, method: :delete, 
                                data: {confirm: "You sure?"} %>
        <% end %>
    </div>
    <div class="vote">
        <span><%= micropost.votes.count %></span>
        <% if (micropost.votes.exists?(user_id: current_user.id)) %>
            <%= form_for(micropost.votes.find_by(user_id: current_user.id),
                         html: { method: :delete }) do |f| %>
                <button type="submit" class="downvote">
                    <i class="glyphicon glyphicon-arrow-down"></i> Downvote
                </button>
            <% end %>
        <% else %>
            <%= form_for :vote, url: votes_path do |f| %>
                <%= hidden_field_tag :micropost_id, micropost.id %>

                <button type="submit" class="upvote">
                    <i class="glyphicon glyphicon-arrow-up"></i> Upvote
                </button>
            <% end %>
        <% end %>
    </div>
</li>